-- ============================================================================
-- 027_seed_aman_branches.sql - Seed the real Aman branch list (mission 3)
-- Source: ops export query_export_2026-06-30 (292 rows). 42 test/non-retail
-- rows excluded (OM/WE/EF channels, SIS stores, merchant entries, booth,
-- auto-insurance, test rows). external_id preserves Aman's canonical store id.
-- ============================================================================

ALTER TABLE public.aman_branches ADD COLUMN IF NOT EXISTS external_id integer;
CREATE UNIQUE INDEX IF NOT EXISTS uq_aman_branches_external_id ON public.aman_branches(external_id);
COMMENT ON COLUMN public.aman_branches.external_id IS 'Aman canonical store id from the ops system (for reconciliation).';

INSERT INTO public.aman_branches (external_id, name_ar, active) VALUES
  (23, 'Aman - Ain Shams Houria st.', true),
  (55, 'Aman - Assiut Azhar', true),
  (831, 'Aman - Ayyat', true),
  (32, 'Aman - Basion Gharbia', true),
  (1, 'Aman - Dar El Salam', true),
  (52, 'Aman - Degla October 2', true),
  (2, 'Aman - Dewedar Hadaye Quba', true),
  (50, 'Aman - Edko', true),
  (402, 'Aman - EL Bitash', true),
  (3, 'Aman - El Gish', true),
  (403, 'Aman - El Hosary', true),
  (4, 'Aman - El Khalifa', true),
  (17, 'Aman - El Sahel', true),
  (36, 'Aman - Elbagour', true),
  (35, 'Aman - Elibeny Haram', true),
  (47, 'Aman - ElMaleka Faisel', true),
  (46, 'Aman - ElsaffCity', true),
  (71, 'Aman - ElTiben', true),
  (33, 'Aman - ElWasta', true),
  (5, 'Aman - FSL Kaabish', true),
  (21, 'Aman - Galleria 40', true),
  (7, 'Aman - Hadayee Helwan', true),
  (29, 'Aman - Hanovile', true),
  (37, 'Aman - Hyper Badr Store', true),
  (34, 'Aman - Hyper Solymanya Store', true),
  (8, 'Aman - Khosos', true),
  (39, 'Aman - Luxor Mahta', true),
  (9, 'Aman - Maadi Ahmed Zaki', true),
  (31, 'Aman - Mahmoudia', true),
  (48, 'Aman - Mansheat Elbakari Faisel', true),
  (40, 'Aman - Mansoura 2', true),
  (44, 'Aman - Maragha Retail', true),
  (54, 'Aman - Matrouh 2', true),
  (830, 'Aman - Mo2saset El Zaka', true),
  (41, 'Aman - Moon Yard Mall', true),
  (42, 'Aman - Nagaahamady 2', true),
  (828, 'Aman - Omraneya2', true),
  (22, 'Aman - Palm Strip', true),
  (12, 'Aman - Qebaa', true),
  (13, 'Aman - Qumia Embaba', true),
  (14, 'Aman - Roud El Farag', true),
  (15, 'Aman - Saab Saleh Ain Shams', true),
  (24, 'Aman - Salam City', true),
  (829, 'Aman - Salam City2', true),
  (43, 'Aman - Saqulta Retail', true),
  (25, 'Aman - Sawah Amirya', true),
  (16, 'Aman - Sayeda Zeinab', true),
  (30, 'Aman - shohdaa', true),
  (322, 'Aman – Shoubra El Kheima', true),
  (18, 'Aman - Sudan Mohandesein', true),
  (19, 'Aman - Wehda Embaba', true),
  (20, 'Aman - Zawya Hamra', true),
  (823, 'Aman- 45 Alex', true),
  (827, 'Aman- Qus', true),
  (401, 'Aman- Ras El Teen', true),
  (571, 'Aman-15th May', true),
  (699, 'Aman-Abnob', true),
  (779, 'Aman-Abo ElMatamir', true),
  (734, 'Aman-Abo_Homos', true),
  (803, 'Aman-Abohomos2', true),
  (513, 'Aman-AboKbeer', true),
  (791, 'Aman-AbuQurqas', true),
  (319, 'Aman-Aga', true),
  (361, 'Aman-Ain Shams ST', true),
  (27, 'Aman-AlAlamein', true),
  (377, 'Aman-AlexWengt', true),
  (344, 'Aman-ArabMaadi', true),
  (531, 'Aman-Ardelewa', true),
  (533, 'Aman-Assuit', true),
  (558, 'Aman-AsuitRgheb', true),
  (550, 'Aman-Aswan', true),
  (626, 'Aman-Atlshelwan', true),
  (733, 'Aman-Atsa_Fayoum', true),
  (337, 'Aman-Bab Ellouq', true),
  (568, 'Aman-Bab kalq', true),
  (712, 'Aman-Badrshen', true),
  (526, 'Aman-Bahteem', true),
  (393, 'Aman-Bakkos', true),
  (577, 'Aman-Balbes', true),
  (386, 'Aman-Banha', true),
  (583, 'Aman-BaniMazar', true),
  (832, 'Aman-BaniMazar2', true),
  (379, 'Aman-Baniswef', true),
  (836, 'Aman-Barakat Al-Saba', true),
  (532, 'Aman-Basateen', true),
  (529, 'Aman-Bashteel', true),
  (837, 'Aman-Bashteel New', true),
  (580, 'Aman-Belqas', true),
  (26, 'Aman-Bragel2', true),
  (805, 'Aman-CarfMaadi', true),
  (781, 'Aman-Daermowas', true),
  (649, 'Aman-Dairout', true),
  (561, 'Aman-DaliaSt.', true),
  (51, 'Aman-Damanhour 2', true),
  (523, 'Aman-Damnhour', true),
  (535, 'Aman-Demrdash', true),
  (563, 'Aman-Domyat', true),
  (400, 'Aman-Domyat 2', true),
  (700, 'Aman-Edfu', true),
  (585, 'Aman-EL Fashn', true),
  (693, 'Aman-El Galaa', true),
  (697, 'Aman-El Kousaia', true),
  (691, 'Aman-El Nozha 2', true),
  (584, 'Aman-EL Sadat', true),
  (730, 'Aman-El_Sahboury2', true),
  (627, 'Aman-Elaagamy', true),
  (370, 'Aman-ELAbbasia', true),
  (790, 'Aman-ElAmryaAlx', true),
  (519, 'Aman-ElAsafra', true),
  (671, 'Aman-ElBadary', true),
  (801, 'Aman-ElGehyna', true),
  (545, 'Aman-Elhadara', true),
  (520, 'Aman-Elmandra', true),
  (367, 'Aman-ElManyal', true),
  (380, 'Aman-Elmarg', true),
  (796, 'Aman-ElMarg2', true),
  (808, 'Aman-El-Monieb', true),
  (378, 'Aman-ElMonofia2', true),
  (787, 'Aman-ElsaaFaisl', true),
  (731, 'Aman-ElSeiouf-Alex', true),
  (698, 'Aman-ElSembelawen', true),
  (625, 'Aman-Emamgazaly', true),
  (695, 'Aman-Esna', true),
  (696, 'Aman-Etay El Barod', true),
  (810, 'Aman-Ezbetnakhl', true),
  (528, 'Aman-EzzDenOmar', true),
  (327, 'Aman-Faisel St.', true),
  (582, 'Aman-Farshot', true),
  (553, 'Aman-Fayoum', true),
  (835, 'Aman-Fayoum Masala', true),
  (725, 'Aman-Fuoa', true),
  (540, 'Aman-Gamra', true),
  (573, 'Aman-Gerga', true),
  (824, 'Aman-Ghamra2', true),
  (362, 'Aman-GolfCtyMal', true),
  (335, 'Aman-Hadayek Ahram', true),
  (316, 'Aman-Haowmdya', true),
  (517, 'Aman-HayprOne', true),
  (329, 'Aman-Helmyet El Zaytoon', true),
  (338, 'Aman-Helwan Ragheb st.', true),
  (340, 'Aman-Herafien', true),
  (534, 'Aman-HoochEissa', true),
  (359, 'Aman-Hsnendsoky', true),
  (673, 'Aman-Hurghada', true),
  (833, 'Aman-Hurghada2', true),
  (552, 'Aman-Hyper-One-Zayed-Store', true),
  (783, 'Aman-Ibrahimya', true),
  (547, 'Aman-Imbaba', true),
  (366, 'Aman-Ismailia', true),
  (785, 'Aman-KafrDawar', true),
  (49, 'Aman-KafrDawar 2', true),
  (324, 'Aman-KafrShekh', true),
  (780, 'Aman-KafrShekh2', true),
  (524, 'Aman-Kafrzyat', true),
  (804, 'Aman-Karmooz', true),
  (574, 'Aman-Kerdasa', true),
  (826, 'Aman-KfrThorms', true),
  (639, 'Aman-Khaldwalid', true),
  (311, 'Aman-Khosous2', true),
  (360, 'Aman-koliat albanat', true),
  (694, 'Aman-Kom Ombo', true),
  (544, 'Aman-Komhamada', true),
  (811, 'Aman–Luxor', true),
  (525, 'Aman-Madkour', true),
  (516, 'Aman-Maghagha', true),
  (372, 'Aman-Mahala', true),
  (802, 'Aman-Mahala2', true),
  (751, 'Aman-MahAssuit', true),
  (752, 'Aman-MahBanha', true),
  (754, 'Aman-MahDamnhor', true),
  (750, 'Aman-MahEmaddin', true),
  (753, 'Aman-MahMansora', true),
  (838, 'Aman-Makram Ebied 2', true),
  (522, 'Aman-Malawy', true),
  (555, 'Aman-Malawy2', true),
  (527, 'Aman-Maleksaleh', true),
  (588, 'Aman-Manfalot', true),
  (521, 'Aman-ManshyaAlex', true),
  (376, 'Aman-Mansoura', true),
  (381, 'Aman-Masrwsudan', true),
  (336, 'Aman-Matarya', true),
  (374, 'Aman-Matarya2', true),
  (782, 'Aman-Matrouh', true),
  (365, 'Aman-MeetGhamr', true),
  (723, 'Aman-MegaAswan', true),
  (726, 'Aman-Menia_AboHlal', true),
  (622, 'Aman-Meniakamh', true),
  (368, 'Aman-MeniaMhata', true),
  (618, 'Aman-MeniaOct', true),
  (567, 'Aman-Menoof', true),
  (331, 'Aman-Mokattam', true),
  (371, 'Aman-Mokattam2', true),
  (326, 'Aman-Mostafa Hafiz Ain Shams', true),
  (392, 'Aman-Muharambek', true),
  (619, 'Aman-Nagahamday', true),
  (341, 'Aman-Nahia', true),
  (792, 'Aman-NaserBnswf', true),
  (778, 'Aman-NewRehab', true),
  (356, 'Aman-Nozha', true),
  (651, 'Aman-Nqada Qena', true),
  (369, 'Aman-Nsrhyasher', true),
  (332, 'Aman-Omraneya', true),
  (318, 'Aman-OroubaSt.', true),
  (312, 'Aman-Owsem', true),
  (363, 'Aman-PortSaied', true),
  (548, 'Aman-Qaha', true),
  (551, 'Aman-QenaMahtta', true),
  (556, 'Aman-QnaAbostet', true),
  (786, 'Aman-Qweisna', true),
  (617, 'Aman-Rebeagezy', true),
  (797, 'Aman-Rshedbhyra', true),
  (317, 'Aman-Saftelaban', true),
  (653, 'Aman-Sahelslim', true),
  (530, 'Aman-SahlHamza', true),
  (375, 'Aman-Sakrkoresh', true),
  (382, 'Aman-SakytMeky', true),
  (586, 'Aman-Samalot', true),
  (825, 'Aman-Samalot2', true),
  (806, 'Aman-Sanories', true),
  (315, 'Aman-SedyBeshr', true),
  (328, 'Aman-Seket El Waily', true),
  (834, 'Aman-Seket El Waily2', true),
  (343, 'Aman-Shaboury', true),
  (578, 'Aman-ShbenQnatr', true),
  (713, 'Aman-Shobra_Oraby', true),
  (549, 'Aman-ShoubraSt.', true),
  (330, 'Aman-Shubra Elkheima 2', true),
  (692, 'Aman-Sidi Gaber', true),
  (557, 'Aman-Skymall', true),
  (313, 'Aman-SlemnGohar', true),
  (543, 'Aman-Souhag', true),
  (305, 'Aman-Suiz', true),
  (514, 'Aman-Taersa', true),
  (621, 'Aman-Tagmoaawel', true),
  (628, 'Aman-Tahta', true),
  (357, 'Aman-Talbyafisl', true),
  (342, 'Aman-TalbyaHaram', true),
  (640, 'Aman-Taltharab', true),
  (789, 'Aman-Tamya', true),
  (510, 'Aman-Tanta2', true),
  (364, 'Aman-TantaBaher', true),
  (724, 'Aman-Tema', true),
  (587, 'Aman-TeretGabal', true),
  (732, 'Aman-Tosson_Alex', true),
  (391, 'Aman-TratSwahel', true),
  (784, 'Aman-TratSwahel2', true),
  (813, 'Aman-WadiGedid', true),
  (648, 'Aman-WardinAlex', true),
  (511, 'Aman-Zagazig', true),
  (394, 'Aman-Zenenbulak', true)
ON CONFLICT (external_id) DO NOTHING;

